# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/simple-step-boot/myhipster
  tag: 0.0.12
  pullPolicy: IfNotPresent

# https://github.com/helm/helm/issues/4490
persistence:
  deploy: true

# official-postgresql:
#   fullnameOverride: official-pg
#   postgresqlUsername: root
#   postgresqlDatabase: myhipster
#   existingSecret: postgresql-secret

# postgresqlSecret:
#   postgresqlPassword:

official-mysql:
#   fullnameOverride: official-mysql
  mysqlDatabase: myhipster
  mysqlUser: myhipster
  existingSecret: mysql-secret

# define environment variables here as a map of key: value
env:
  SPRING_DATASOURCE_URL: jdbc:mysql://official-mysql:3306/myhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  SPRING_DATASOURCE_USERNAME: myhipster
  SPRING_DATASOURCE_PASSWORD: myhipster

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: myhipster
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /management/health
livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 6
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 1
