apiVersion: extensions/v1beta1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  mysql-password: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
