apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mysql-password: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
