apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresqlSecret.postgresqlPassword | b64enc | quote }}